Update update-files.yml

diff --git a/.github/workflows/update-files.yml b/.github/workflows/update-files.yml
--- a/.github/workflows/update-files.yml
+++ b/.github/workflows/update-files.yml
@@ -7,6 +7,7 @@ on:
       - 'xdy/files/mb/**'
       - 'xdy/files/mt/**'
       - 'xdy/files/others/**'
+  workflow_dispatch:
 
 jobs:
   update-json:
@@ -15,6 +16,14 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
+
+    - name: Cache Node.js modules
+      uses: actions/cache@v3
+      with:
+        path: ~/.npm
+        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+        restore-keys: |
+          ${{ runner.os }}-node-
 
     - name: Set up Node.js
       uses: actions/setup-node@v3
@@ -25,7 +34,10 @@ jobs:
       run: npm install
 
     - name: Run script to generate files JSONs
-      run: node scripts/generate-files.js
+      run: |
+        echo "Starting to generate JSON files..."
+        node scripts/generate-files.js
+        echo "JSON files generated successfully."
 
     - name: Commit and push changes
       env:
@@ -36,8 +48,8 @@ jobs:
         git add xdy/files-mr.json xdy/files-mb.json xdy/files-mt.json xdy/files-others.json
         if [ -n "$(git status --porcelain)" ]; then
           git commit -m "Automatically update files JSONs"
-          git push
+          if ! git push; then
+            echo "Failed to push changes to the repository."
+            exit 1
+          fi
         fi
-
-
-
