Add files via upload

diff --git a/.github/workflows/update-files.yml b/.github/workflows/update-files.yml
--- a/.github/workflows/update-files.yml
+++ b/.github/workflows/update-files.yml
@@ -40,16 +40,19 @@ jobs:
         echo "JSON files generated successfully."
 
     - name: Commit and push changes
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: |
-        git config --global user.name github-actions
-        git config --global user.email github-actions@github.com
-        git add files-mr.json files-mb.json files-mt.json files-others.json
-        if [ -n "$(git status --porcelain)" ]; then
-          git commit -m "Automatically update files JSONs"
-          if ! git push; then
-            echo "Failed to push changes to the repository."
-            exit 1
-          fi
-        fi
+  env:
+    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  run: |
+    git config --global user.name github-actions
+    git config --global user.email github-actions@github.com
+    # 撤销 package.json 和 package-lock.json 的更改
+    git restore package.json
+    git clean -f package-lock.json
+    git add files-mr.json files-mb.json files-mt.json files-others.json
+    if [ -n "$(git status --porcelain)" ]; then
+      git commit -m "Automatically update files JSONs"
+      if ! git push; then
+        echo "Failed to push changes to the repository."
+        exit 1
+      fi
+    fi
